apache:
    vhosts:
        opportunivel:
            servername: opportunivel.dev
            serveraliases:
                - www.local.dev
            docroot: /var/www/opportunivel/public
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            directories:
                avd_3pfxsxp65rzg:
                    path: /var/www/opportunivel/public
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    provider: directory
                    files_match:
                        jsrdkbzi2z1h:
                            provider: filesmatch
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''