vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: puphpet/ubuntu1604-x64
                box_url: puphpet/ubuntu1604-x64
                box_version: '0'
                chosen_virtualizer: vmware_fusion
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                        ethernet0.pcislotnumber: 32
                        ethernet1.pcislotnumber: 33
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    vflm_16wifcf45ve4:
                        id: localvm
                        hostname: local.dev
                        network:
                            private_network: 192.168.57.101
                            forwarded_port:
                                vflmnfp_8k1t127b7has:
                                    host: '9787'
                                    guest: '22'
                        memory: '1024'
                        cpus: '1'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_sfmpfnkylfqu:
                source: ~/Sites
                target: /var/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: vagrant
                group: www-data
                mount_options: ["dmode=775,fmode=664"]
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'true'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - vim
        - htop
        - libnotify-bin
        - libxrender1
        - libfontconfig1
        - libxext6
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: en_US.UTF-8
        locales:
            - en_US.UTF-8
        timezone: America/Chicago
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '0'
    settings:
        version: present
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts: {  }
    proxies: {  }
apache:
    install: '1'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
        - expires
        - headers
        - vhost_alias
        - deflate
    vhosts:
        zzzw_laravel_local_dev:
            servername: lvl.local.dev
            serveraliases:
                - '*.lvl.dev'
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /vagrant/puphpet/dev.lvl.conf
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_k0brl484dbmb:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
            files_match:
                avdfm_f9kkbza7ycy9:
                    path: \.php$
                    sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
                    custom_fragment: ''
                    provider: filesmatch
        zzzw_laravel_local_dev_ssl:
            servername: lvl.local.dev
            serveraliases:
                - '*.lvl.dev'
            docroot: /var/www
            port: '443'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /vagrant/puphpet/dev.lvl.conf
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_k0brl484dbmb_ssl:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
            files_match:
                avdfm_f9kkbza7ycy9_ssl:
                    path: \.php$
                    sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
                    custom_fragment: ''
                    provider: filesmatch
        zzzx_wordpress_local_dev:
            servername: wp.local.dev
            serveraliases:
                - '*.wp.dev'
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /vagrant/puphpet/dev.wp.conf
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_k0brl373dbma:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
            files_match:
                avdfm_f9kkbza7ybx8:
                    path: \.php$
                    sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
                    custom_fragment: ''
                    provider: filesmatch
        zzzx_wordpress_local_dev_ssl:
            servername: wp.local.dev
            serveraliases:
                - '*.wp.dev'
            docroot: /var/www
            port: '443'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /vagrant/puphpet/dev.wp.conf
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_k0brl373dbma_ssl:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
            files_match:
                avdfm_f9kkbza7ybx8_ssl:
                    path: \.php$
                    sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
                    custom_fragment: ''
                    provider: filesmatch
        zzzy_local_dev:
            servername: local.dev
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /vagrant/puphpet/dev.local.conf
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_k0brl262dbma:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
            files_match:
                avdfm_f9kkbza7ybw7:
                    path: \.php$
                    sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
                    custom_fragment: ''
                    provider: filesmatch
        zzzy_local_dev_ssl:
            servername: local.dev
            docroot: /var/www
            port: '443'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /vagrant/puphpet/dev.local.conf
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_k0brl262dbma_ssl:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
            files_match:
                avdfm_f9kkbza7ybw7_ssl:
                    path: \.php$
                    sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
                    custom_fragment: ''
                    provider: filesmatch
        zzzz_wildcard_dev:
            servername: wildcard.dev
            serveraliases:
                - '*.dev'
            docroot: /var/www
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /vagrant/puphpet/dev.conf
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                zzz_k0brl262dbma:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
            files_match:
                zzzfm_f9kkbza7ybw7:
                    path: \.php$
                    sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
                    custom_fragment: ''
                    provider: filesmatch
        zzzz_wildcard_dev_ssl:
            servername: wildcard.dev
            serveraliases:
                - '*.dev'
            docroot: /var/www
            port: '443'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: /vagrant/puphpet/dev.conf
            ssl: '1'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                zzz_k0brl262dbma_ssl:
                    path: /var/www
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
            files_match:
                zzzfm_f9kkbza7ybw7_ssl:
                    path: \.php$
                    sethandler: 'proxy:unix:/var/run/php5-fpm.sock|fcgi://localhost'
                    custom_fragment: ''
                    provider: filesmatch
letsencrypt:
    install: '1'
    settings:
        email: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.1'
    modules:
        php:
            - cli
            - intl
            - curl
            - gd
            - imagick
            - ldap
            - mbstring
            - mysql
            - odbc
            - sqlite
            - xml
            - xmlrpc
            - xsl
            - zip
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: America/Chicago
        max_input_vars: '10000'
        post_max_size: 32M
        upload_max_filesize: 32M
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_iptnfrowb2np:
            ini:
                prefix: www
                listen: '/var/run/php5-fpm.sock'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.24.1
drush:
    install: '0'
    version: 8.0.5
ruby:
    install: '1'
    versions:
        rv_j9wfat123e2y:
            default: '1'
            bundler: '1'
            version: 2.3.1
            gems:
                - deep_merge@1.0.1
                - activesupport@4.2.6
                - vine@0.2
                - sass
                - capistrano
                - capistrano-bundler
                - capistrano-composer
                - capistrano-laravel
                - capistrano-npm
                - capistrano-bower
                - capistrano-gulp
                - highline
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '6'
    npm_packages:
        - bower
        - gulp
        - gulp-sass
        - gulp-ruby-sass
        - gulp-sourcemaps
        - gulp-uglify
        - gulp-autoprefixer
yarn:
    install: '1'
hhvm:
    install: '0'
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users: {  }
    databases: {  }
    grants: {  }
mysql:
    install: '1'
    settings:
        version: '5.7'
        root_password: '123'
        override_options:
            mysqld:
                character-set-server: 'utf8mb4'
    adminer: '0'
    users: {  }
    databases: {  }
    grants: {  }
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: '2.6'
    databases: {  }
redis:
    install: '0'
    settings:
        port: '6379'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.3.1
        java_install: true
    instances:
        esi_ug3e1gu802f3:
            name: es-01
solr:
    install: '0'
    settings:
        version: 5.5.2
        port: '8984'

